use crate::{
    error::{Error, Result},
    knots::Knots,
    parameters::Parameters,
    types::VecD,
};

fn input_check(degree: usize, polygon_segments: usize) -> Result<()> {
    match degree {
        0 => Err(Error::DegreeTooLow { degree }),
        degree if degree > polygon_segments => Err(Error::TooFewPolygonSegments { degree, polygon_segments }),
        _ => Ok(()),
    }
}

/// Generates a clamped, uniform knot vector — eq. (9.7) in `Piegl1997`:
///
/// uᵢ₊ₚ = i ∕ (n − p + 1),   i = 1, …, n − p
///
/// with the knots u, the degree p, and the number of polygon segments n.
///
/// ## Note
/// Use this method only if the control points are evenly distributed.
pub fn uniform(degree: usize, polygon_segments: usize) -> Result<Knots> {
    input_check(degree, polygon_segments)?;

    let internal_knot_count = polygon_segments - degree;

    let mut knots = VecD::zeros(degree + polygon_segments + 2);

    for i in 1..=internal_knot_count {
        knots[degree + i] = i as f64 / (internal_knot_count + 1) as f64
    }

    // Set the tail clamp to one.
    for i in polygon_segments + 1..knots.len() {
        knots[i] = 1.;
    }

    Ok(Knots::new(degree, knots))
}

/// Generates the knot vector by averaging consecutive parameters — eq. (9.8) in `Piegl1997`:
///
/// uⱼ₊ₚ = (ūⱼ + ⋯ + ūⱼ₊ₚ₋₁) ∕ p,   j = 1, …, n − p
///
/// with the knots u, the parameters ū, the degree p, and the number of polygon segments n.
pub fn averaging(degree: usize, polygon_segments: usize, parameters: &Parameters) -> Result<Knots> {
    input_check(degree, polygon_segments)?;

    let internal_knot_count = polygon_segments - degree;

    let u_bar = parameters.vector();

    let mut knots = VecD::zeros(degree + polygon_segments + 2);

    for j in 1..=internal_knot_count {
        let mut parameter_sum = 0.;

        for i in j..j + degree {
            parameter_sum += u_bar[i];
        }
        knots[degree + j] = parameter_sum / degree as f64;
    }

    // Set the tail clamp to one.
    for j in polygon_segments + 1..knots.len() {
        knots[j] = 1.;
    }

    Ok(Knots::new(degree, knots))
}

/// Generates the knot vector by de Boor's averaging over parameter spans — eqs. (9.68) and (9.69) in `Piegl1997`:
///
/// d = (n + 1) ∕ (n − p + 1),   uⱼ₊ₚ = (1 − α) ūᵢ₋₁ + α ūᵢ,   i = ⌊j·d⌋,   α = j·d − i
///
/// with the knots u, the parameters ū, the degree p, the number of polygon segments n,
/// the span width d, and the interpolation weight α.
///
/// ## Note
/// If this method is used, the parameters must be generated by the chord-length method
/// to prevent the resulting system of linear equations from becoming singular.
/// It guarantees that every knot span contains at least one parameter.
/// According to de Boor, this ensures that the coefficient matrix is positive definite and
/// well-conditioned, which is important for the least-squares fitting and interpolation of data points.
pub fn de_boor(degree: usize, polygon_segments: usize, parameters: &Parameters) -> Result<Knots> {
    input_check(degree, polygon_segments)?;

    let u_bar = parameters.vector();

    let internal_knot_count = polygon_segments - degree;
    let internal_knot_spans = internal_knot_count + 1;

    let span_width = (polygon_segments + 1) as f64 / internal_knot_spans as f64;

    let mut knots = VecD::zeros(degree + polygon_segments + 2);

    for j in 1..=internal_knot_count {
        let position = j as f64 * span_width;

        let i = position as usize;
        let alpha = position - i as f64;

        knots[degree + j] = (1f64 - alpha) * u_bar[i - 1] + alpha * u_bar[i];
    }

    // Set the tail clamp to one.
    for j in polygon_segments + 1..knots.len() {
        knots[j] = 1.;
    }

    Ok(Knots::new(degree, knots))
}

#[cfg(test)]
mod tests {
    use nalgebra::dvector;

    use crate::parameters::methods::equally_spaced;

    use super::*;

    mod uniform {
        use rstest::rstest;

        use super::*;

        #[test]
        fn degree_0_errors() {
            let degree = 0;
            let polygon_segments = degree + 1;
            assert!(uniform(degree, polygon_segments).is_err());
        }

        #[test]
        fn degree_1() {
            assert_eq!(uniform(1, 4).unwrap().derivatives[0], dvector![0., 0., 0.25, 0.5, 0.75, 1., 1.]);
        }

        #[test]
        fn degree_2() {
            assert_eq!(uniform(2, 4).unwrap().derivatives[0], dvector![0., 0., 0., 1. / 3., 2. / 3., 1., 1., 1.]);
        }

        #[test]
        fn degree_3() {
            assert_eq!(uniform(3, 4).unwrap().derivatives[0], dvector![0., 0., 0., 0., 0.5, 1., 1., 1., 1.]);
        }

        #[rstest(degree, case(1), case(2), case(3))]
        fn segments_eq_degree(degree: usize) {
            let polygon_segments = degree;
            let head = vec![0.0; degree + 1];
            let tail = vec![1.0; degree + 1];

            assert_eq!(
                uniform(degree, polygon_segments).unwrap().derivatives[0],
                VecD::from_vec([head, tail].concat())
            );
        }

        #[rstest(degree, case(1), case(2), case(3))]
        fn segments_eq_degree_plus_1(degree: usize) {
            let polygon_segments = degree + 1;
            let head = vec![0.0; degree + 1];
            let internal = vec![0.5];
            let tail = vec![1.0; degree + 1];

            assert_eq!(
                uniform(degree, polygon_segments).unwrap().derivatives[0],
                VecD::from_vec([head, internal, tail].concat())
            );
        }

        #[rstest(degree, case(1), case(2), case(3))]
        fn segments_eq_degree_plus_2(degree: usize) {
            let polygon_segments = degree + 2;

            let head = vec![0.0; degree + 1];
            let internal = vec![1.0 / 3.0, 2.0 / 3.0];
            let tail = vec![1.0; degree + 1];

            assert_eq!(
                uniform(degree, polygon_segments).unwrap().derivatives[0],
                VecD::from_vec([head, internal, tail].concat())
            );
        }
    }

    mod averaging {
        use rstest::rstest;

        use crate::knots::methods::averaging;

        use super::*;

        #[test]
        fn degree_0_errors() {
            let degree = 0;
            let polygon_segments = degree + 1;
            let parameters = equally_spaced(polygon_segments);

            assert!(averaging(degree, polygon_segments, &parameters).is_err());
        }

        #[test]
        fn degree_1() {
            let polygon_segments = 4;
            let parameters = equally_spaced(polygon_segments);
            assert_eq!(
                averaging(1, polygon_segments, &parameters).unwrap().derivatives[0],
                dvector![0., 0., 0.25, 0.5, 0.75, 1., 1.]
            );
        }

        #[test]
        fn degree_2() {
            let polygon_segments = 4;
            let parameters = equally_spaced(polygon_segments);
            assert_eq!(
                averaging(2, polygon_segments, &parameters).unwrap().derivatives[0],
                dvector![0., 0., 0., 0.375, 0.625, 1., 1., 1.]
            );
        }

        #[test]
        fn degree_3() {
            let polygon_segments = 4;
            let parameters = equally_spaced(polygon_segments);
            assert_eq!(
                averaging(3, polygon_segments, &parameters).unwrap().derivatives[0],
                dvector![0., 0., 0., 0., 0.5, 1., 1., 1., 1.]
            );
        }

        #[rstest(degree, case(1), case(2), case(3))]
        fn segments_eq_degree(degree: usize) {
            let polygon_segments = degree;
            let parameters = equally_spaced(polygon_segments);

            let head = vec![0.0; degree + 1];
            let tail = vec![1.0; degree + 1];
            assert_eq!(
                averaging(degree, polygon_segments, &parameters).unwrap().derivatives[0],
                VecD::from_vec([head, tail].concat())
            );
        }

        #[rstest(degree, case(1), case(2), case(3))]
        fn segments_eq_degree_plus_1(degree: usize) {
            let polygon_segments = degree + 1;
            let parameters = equally_spaced(polygon_segments);

            let head = vec![0.0; degree + 1];
            let internal = vec![0.5];
            let tail = vec![1.0; degree + 1];

            assert_eq!(
                averaging(degree, polygon_segments, &parameters).unwrap().derivatives[0],
                VecD::from_vec([head, internal, tail].concat())
            );
        }
    }

    mod de_boor {
        use approx::assert_relative_eq;
        use nalgebra::dvector;
        use rstest::rstest;

        use super::*;

        #[test]
        fn degree_0_errors() {
            let degree = 0;
            let polygon_segments = degree + 1;
            let parameters = equally_spaced(polygon_segments);

            assert!(de_boor(degree, polygon_segments, &parameters).is_err());
        }

        #[test]
        fn degree_1() {
            let polygon_segments = 4;
            let parameters = equally_spaced(polygon_segments);
            assert_eq!(
                de_boor(1, polygon_segments, &parameters).unwrap().derivatives[0],
                dvector![0., 0., 0.0625, 0.375, 0.6875, 1., 1.]
            );
        }

        #[test]
        fn degree_2() {
            let polygon_segments = 4;
            let parameters = equally_spaced(polygon_segments);
            assert_relative_eq!(
                de_boor(2, polygon_segments, &parameters).unwrap().derivatives[0],
                dvector![0., 0., 0., 1. / 6., 1. / 3. + 0.25, 1., 1., 1.],
                epsilon = f64::EPSILON.sqrt()
            );
        }

        #[test]
        fn degree_3() {
            let polygon_segments = 4;
            let parameters = equally_spaced(polygon_segments);
            assert_eq!(
                de_boor(3, polygon_segments, &parameters).unwrap().derivatives[0],
                dvector![0., 0., 0., 0., 0.375, 1., 1., 1., 1.]
            );
        }

        #[rstest(degree, case(1), case(2), case(3))]
        fn segments_eq_degree(degree: usize) {
            let polygon_segments = degree;
            let parameters = equally_spaced(polygon_segments);

            let head = vec![0.0; degree + 1];
            let tail = vec![1.0; degree + 1];
            assert_eq!(
                de_boor(degree, polygon_segments, &parameters).unwrap().derivatives[0],
                VecD::from_vec([head, tail].concat())
            );
        }

        #[rstest(degree, internal_knot, case(1, 1. / 4.), case(2, 2. / 6.), case(3, 3. / 8.))]
        fn segments_eq_degree_plus_1(degree: usize, internal_knot: f64) {
            let polygon_segments = degree + 1;
            let parameters = equally_spaced(polygon_segments);

            let head = vec![0.0; degree + 1];
            let internal = vec![internal_knot];
            let tail = vec![1.0; degree + 1];

            assert_eq!(
                de_boor(degree, polygon_segments, &parameters).unwrap().derivatives[0],
                VecD::from_vec([head, internal, tail].concat())
            );
        }
    }
}
