name: CI

on:
  push:
    branches: [ main, next ]
  pull_request:
  workflow_dispatch:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install Rust nightly rustfmt
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Show Rust version
        run: rustc --version

      - name: Install fontconfig
        run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: just build

      - name: Run tests
        run: just test

      - name: Lint
        run: just clippy

      - name: Build docs
        run: just doc

      - name: Run rustfmt
        run: just fmt-check

      - name: Install taplo
        uses: taiki-e/install-action@v2
        with:
          tool: taplo

      - name: Run taplo
        run: just taplo-check
